In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [31]:
df=pd.read_csv('/Churn_Modelling.csv')
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [32]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
label = le.fit_transform(df['Geography'])
label

array([0, 2, 0, ..., 0, 1, 0])

In [33]:
df.drop("Geography", axis=1, inplace=True)
df["Geography"] = label
df

RowNumber  CustomerId    Surname  CreditScore  Gender  Age  Tenure  \
0             1    15634602   Hargrave          619  Female   42       2   
1             2    15647311       Hill          608  Female   41       1   
2             3    15619304       Onio          502  Female   42       8   
3             4    15701354       Boni          699  Female   39       1   
4             5    15737888   Mitchell          850  Female   43       2   
...         ...         ...        ...          ...     ...  ...     ...   
9995       9996    15606229   Obijiaku          771    Male   39       5   
9996       9997    15569892  Johnstone          516    Male   35      10   
9997       9998    15584532        Liu          709  Female   36       7   
9998       9999    15682355  Sabbatini          772    Male   42       3   
9999      10000    15628319     Walker          792  Female   28       4   

        Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  \
0          0.00              1          1               1        101348.88   
1      83807.86              1          0               1        112542.58   
2     159660.80              3          1               0        113931.57   
3          0.00              2          0               0         93826.63   
4     125510.82              1          1               1         79084.10   
...         ...            ...        ...             ...              ...   
9995       0.00              2          1               0         96270.64   
9996   57369.61              1          1               1        101699.77   
9997       0.00              1          0               1         42085.58   
9998   75075.31              2          1               0         92888.52   
9999  130142.79              1          1               0         38190.78   

      Exited  Geography  
0          1          0  
1          0          2  
2          1          0  
3          0          0  
4          0          2  
...      ...        ...  
9995       0          0  
9996       0          0  
9997       1          0  
9998       1          1  
9999       0          0  

[10000 rows x 14 columns]

In [34]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
label = le.fit_transform(df['Gender'])
label

array([0, 0, 0, ..., 0, 1, 0])

In [35]:
df.drop("Gender", axis=1, inplace=True)
df["Gender"] = label
df

RowNumber  CustomerId    Surname  CreditScore  Age  Tenure    Balance  \
0             1    15634602   Hargrave          619   42       2       0.00   
1             2    15647311       Hill          608   41       1   83807.86   
2             3    15619304       Onio          502   42       8  159660.80   
3             4    15701354       Boni          699   39       1       0.00   
4             5    15737888   Mitchell          850   43       2  125510.82   
...         ...         ...        ...          ...  ...     ...        ...   
9995       9996    15606229   Obijiaku          771   39       5       0.00   
9996       9997    15569892  Johnstone          516   35      10   57369.61   
9997       9998    15584532        Liu          709   36       7       0.00   
9998       9999    15682355  Sabbatini          772   42       3   75075.31   
9999      10000    15628319     Walker          792   28       4  130142.79   

      NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  Exited  \
0                 1          1               1        101348.88       1   
1                 1          0               1        112542.58       0   
2                 3          1               0        113931.57       1   
3                 2          0               0         93826.63       0   
4                 1          1               1         79084.10       0   
...             ...        ...             ...              ...     ...   
9995              2          1               0         96270.64       0   
9996              1          1               1        101699.77       0   
9997              1          0               1         42085.58       1   
9998              2          1               0         92888.52       1   
9999              1          1               0         38190.78       0   

      Geography  Gender  
0             0       0  
1             2       0  
2             0       0  
3             0       0  
4             2       0  
...         ...     ...  
9995          0       1  
9996          0       1  
9997          0       0  
9998          1       1  
9999          0       0  

[10000 rows x 14 columns]

In [36]:
x=df.drop(['Exited','Surname'],axis=1)
y=df['Exited']

In [37]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20)

# Random Forest Classifier

In [38]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 100)
rf.fit(x_train,y_train)

RandomForestClassifier()

In [39]:
y_pred1=rf.predict(x_test)

In [40]:
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(y_test,y_pred1))
print(classification_report(y_test,y_pred1))

[[1529   50]
 [ 221  200]]
              precision    recall  f1-score   support

           0       0.87      0.97      0.92      1579
           1       0.80      0.48      0.60       421

    accuracy                           0.86      2000
   macro avg       0.84      0.72      0.76      2000
weighted avg       0.86      0.86      0.85      2000



# XGBoost

In [41]:
from xgboost import XGBClassifier
model = XGBClassifier()
model.fit(x_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [42]:
y_pred2=model.predict(x_test)

In [43]:
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(y_test,y_pred2))
print(classification_report(y_test,y_pred2))

[[1493   86]
 [ 217  204]]
              precision    recall  f1-score   support

           0       0.87      0.95      0.91      1579
           1       0.70      0.48      0.57       421

    accuracy                           0.85      2000
   macro avg       0.79      0.72      0.74      2000
weighted avg       0.84      0.85      0.84      2000



# Logistic Regression

In [44]:
from sklearn.linear_model import LogisticRegression
model2 = LogisticRegression()
model2.fit(x_train, y_train)

LogisticRegression()

In [45]:
y_pred3=model.predict(x_test)

In [46]:
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(y_test,y_pred3))
print(classification_report(y_test,y_pred3))

[[1493   86]
 [ 217  204]]
              precision    recall  f1-score   support

           0       0.87      0.95      0.91      1579
           1       0.70      0.48      0.57       421

    accuracy                           0.85      2000
   macro avg       0.79      0.72      0.74      2000
weighted avg       0.84      0.85      0.84      2000

